---
apiVersion: v1
kind: Pod
metadata:
  name: "cm-svm-test-connection"
  labels:

    helm.sh/chart: cm-svm
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['cm-svm:1080']
  restartPolicy: Never
MANIFEST:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: "cm-svm"
  name: cm-svm
spec:
  type: NodePort
  ports:
    - name: cm-svm
      port: 1080
  selector:
    app: "cm-svm"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-svm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cm-svm"
  template:
    metadata:  
      name: cm-svm
      labels:
        app: "cm-svm"
        
        collectlog: "true"
    spec:
      imagePullSecrets:
        - name: sapcommoncdn
      containers: 
        - name: cm-svm
          image: gtlc-production.common.repositories.cloud.sap/svmservices-dev:PR-139-30
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 1081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 1081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /etc/init.d/tomcat stop || sleep 30
          
          
          ports:
            - containerPort: 1080
          volumeMounts:
            - name: log
              mountPath: /opt/apache-tomcat-7.0.70/logs
        - name: filebeat
          image: gtlc-production.common.cdn.repositories.cloud.sap/filebeat:2
          env:
            - name: GTLC_SRV
              value: "cm-svm"
          volumeMounts:
            - name: log
              mountPath: /opt/apache-tomcat-7.0.70/logs

        - name: logrotate
          image: gtlc-production.common.cdn.repositories.cloud.sap/logrotate:4
          imagePullPolicy: Always          
          volumeMounts:
            - name: log
              mountPath: /opt/apache-tomcat-7.0.70/logs
      volumes:
        - name: log
          emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cm-svm
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https  
spec:
  rules:
    - host: cmsvm
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: cm-svm
                port:
                  number: 443
